###

PUT  http://localhost:5000/api/addItem
Content-Type: application/json

{
    "item":{
        "title":"Mahi",
        "content": "She's a beautiful girl"
    }
}

###
GET http://localhost:5000/api/getItem/Mahi

###
DELETE http://localhost:5000/api/deleteItem/Mahi

###
PUT http://localhost:5000/api/updateItem
Content-Type: application/json

{
    "title":"Mahi",
    "updatedTodo":{
        "title": "Mahi",
        "content":"I love her"

    }
}

### 
POST  http://localhost:5000/authentication/register
Content-Type: application/json

{
    "username":"Maisha Shawrin Mahi",
    "password": "as I am 2023",
    "email":"mahi123@gmail.com"
}

###
POST http://localhost:5000/authentication/login
Content-Type: application/json

{
    "username":"Maisha Shawrin Mahi",
    "password":"as I am 2023"
}